[main]
font=Mozilla Text:size=11
prompt="> "
terminal=kitty
width=30
horizontal-pad=12
vertical-pad=12
inner-pad=8
anchor=center
layer=overlay
lines=8

[colors]
# slightly lifted from pure black for depth
background=080808ee

# main text
text=bdbdbdff
input=ffffffff
prompt=949494ff

# matches (use accent, not white)
match=80a0ffff

# selection (from your kitty theme)
selection=b2ceeeff
selection-text=080808ff

# border (use inactive_border_color, not white)
border=323437ff

[border]
width=1
radius=6
