[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x100F0F"
foreground = "0xCECDC3"

[colors.cursor]
text = "0x100F0F"
cursor = "0xCECDC3"

[colors.selection]
text = "0x100F0F"
background = "0xCECDC3"

[colors.normal]
black   = "0x100F0F"
red     = "0xD14D41"
green   = "0x879A39"
yellow  = "0xD0A215"
blue    = "0x4385BE"
magenta = "0xCE5D97"
cyan    = "0x3AA99F"
white   = "0xCECDC3"

[colors.bright]
black   = "0x575653"
red     = "0xD14D41"
green   = "0x879A39"
yellow  = "0xD0A215"
blue    = "0x4385BE"
magenta = "0xCE5D97"
cyan    = "0x3AA99F"
white   = "0xF2F0E5"

[colors.dim]
black   = "0x403E3C"
red     = "0xAF3029"
green   = "0x66800B"
yellow  = "0xAD8301"
blue    = "0x205EA6"
magenta = "0xA02F6F"
cyan    = "0x24837B"
white   = "0xB7B5AC"
