general {
    ignore_empty_input = true
}

background {
    monitor = HDMI-A-1
    path = ~/.config/hypr/images/wallpaper.png
    blur_passes = 3
}

background {
    monitor = eDP-1
    path = ~/.config/hypr/images/wallpaper.png 
    blur_passes = 3
}

input-field {
    monitor = HDMI-A-1
    size = 300, 50
    position = 0, -100
    dots_center = true
}

input-field {
    monitor = eDP-1
    size = 300, 50
    position = 0, -100
    dots_center = true
}
